# Trigger Mac OS X build (even though this is a Python test)
language: objective-c

before_install:
   - brew update
   - brew upgrade python --without-readline
   - export PATH=/usr/local/bin:$PATH

install:
  - python setup.py install

before_script:
  - pip install pytest

script:
  - py.test test.py
