# Trigger Mac OS X build (even though this is a Python test)
language: objective-c

before_install:
   - brew update
   - brew remove python --ignore-dependencies
   - brew install python --without-readline
   - brew install python3 --without-readline
   - export PATH=/usr/local/bin:$PATH

install:
  - python2 setup.py install
  - python3 setup.py install

before_script:
  - pip2 install pytest
  - pip3 install pytest

script:
  - python2 /usr/local/bin/py.test test.py
  - python3 /usr/local/bin/py.test test.py
